export const SEARCH_FOCUS = "HEADER_SEARCH_FOCUS"
export const SEARCH_BLUR = "HEADER_SEARCH_BLUR"
export const SEARCH_DATA = "HEADER_SEARCH_DATA"
export const MOUSE_ENTER = "HEADER_MOUSE_ENTER"
export const MOUSE_LEAVE = "HEADER_MOUSE_LEAVE"
export const CHANGE_PAGE = "HEADER_CHANGE_PAGE"

